"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import {
  Check,
  Copy,
  Download,
  Image as ImageIcon,
  Instagram,
  Linkedin,
  Loader2,
  FileText,
  Twitter,
  RefreshCw,
} from "lucide-react";
import { useAuth } from "@/lib/auth/auth-context";
import type { ProductAnalysis, CompetitorAnalysis, CompetitiveInsights, BrandVoiceDoc } from "@/lib/agents/schemas";
import type { FridayContext } from "@/lib/agents/core/context";

type SocialCopy = {
  instagram: string;
  x: string;
  linkedin: string;
  raw: string;
};

type SocialCopyCacheRecord =
  | {
      status: "pending";
      startedAt: number;
    }
  | {
      status: "success";
      data: SocialCopy;
    }
  | {
      status: "error";
      error: string;
    };

type WorkspaceProps = {
  siteUrl: string;
  productAnalysis: ProductAnalysis;
  competitors: Array<{ name: string; domain: string; positioning?: string; strengths?: string[]; weaknesses?: string[] }>;
  competitorAnalyses: CompetitorAnalysis[];
  insights: CompetitiveInsights | null;
  brandVoiceDoc: BrandVoiceDoc | null;
  brandContext: FridayContext;
};

function copyText(text: string) {
  return navigator.clipboard.writeText(text);
}

const pendingSocialCopyRequests = new Set<string>();
const PENDING_SOCIAL_COPY_TTL_MS = 5 * 60 * 1000;

function getSocialCopyCacheKey(siteUrl: string) {
  return `friday-social-copy:${siteUrl}`;
}

function readSocialCopyCache(cacheKey: string): SocialCopyCacheRecord | null {
  if (typeof window === "undefined") {
    return null;
  }

  try {
    const raw = window.localStorage.getItem(cacheKey);
    if (!raw) {
      return null;
    }

    const parsed = JSON.parse(raw) as SocialCopyCacheRecord;
    if (!parsed || typeof parsed !== "object" || !("status" in parsed)) {
      return null;
    }

    if (
      parsed.status === "pending" &&
      typeof parsed.startedAt === "number" &&
      Date.now() - parsed.startedAt > PENDING_SOCIAL_COPY_TTL_MS
    ) {
      window.localStorage.removeItem(cacheKey);
      return null;
    }

    return parsed;
  } catch {
    return null;
  }
}

function writeSocialCopyCache(cacheKey: string, value: SocialCopyCacheRecord) {
  if (typeof window === "undefined") {
    return;
  }

  window.localStorage.setItem(cacheKey, JSON.stringify(value));
}

function clearSocialCopyCache(cacheKey: string) {
  if (typeof window === "undefined") {
    return;
  }

  window.localStorage.removeItem(cacheKey);
}

function extractSocialCopyError(raw: string) {
  const trimmed = raw.trim();
  if (!trimmed) {
    return null;
  }

  if (
    /^error:/i.test(trimmed) ||
    /api error:/i.test(trimmed) ||
    /invalid_request_error/i.test(trimmed) ||
    /workspace api usage limits/i.test(trimmed)
  ) {
    return trimmed.replace(/^error:\s*/i, "").trim();
  }

  return null;
}

function isValidSocialCopy(data: SocialCopy) {
  if (extractSocialCopyError(data.raw)) {
    return false;
  }

  return Boolean(data.instagram.trim() || data.x.trim() || data.linkedin.trim());
}

function CopyButton({ text, label }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);

  return (
    <button
      type="button"
      onClick={async () => {
        await copyText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }}
      className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-xs font-medium text-white/62 transition hover:border-white/20 hover:text-white"
    >
      {copied ? <Check size={12} /> : <Copy size={12} />}
      {label ?? (copied ? "Copied" : "Copy")}
    </button>
  );
}

export function Workspace({
  siteUrl,
  productAnalysis,
  competitors,
  competitorAnalyses,
  insights,
  brandVoiceDoc,
  brandContext,
}: WorkspaceProps) {
  const { session } = useAuth();
  const [socialCopy, setSocialCopy] = useState<SocialCopy | null>(null);
  const [isGeneratingCopy, setIsGeneratingCopy] = useState(false);
  const [copyError, setCopyError] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const socialCopyInFlightRef = useRef(false);
  const autoGeneratedKeysRef = useRef(new Set<string>());

  const domain = (() => {
    try { return new URL(siteUrl).hostname.replace(/^www\./, ""); } catch { return siteUrl; }
  })();

  const headers = useMemo(() => {
    const nextHeaders: Record<string, string> = {};
    if (session?.access_token) {
      nextHeaders.Authorization = `Bearer ${session.access_token}`;
    }
    return nextHeaders;
  }, [session?.access_token]);

  const socialCopyCacheKey = useMemo(() => getSocialCopyCacheKey(siteUrl), [siteUrl]);

  // Auto-generate social copy on mount
  const generateSocialCopy = useCallback(async ({ force = false }: { force?: boolean } = {}) => {
    if (socialCopyInFlightRef.current) return;
    if (!force) {
      if (socialCopy) return;

      const cached = readSocialCopyCache(socialCopyCacheKey);
      if (cached?.status === "success" || cached?.status === "error" || cached?.status === "pending") {
        return;
      }

      if (pendingSocialCopyRequests.has(socialCopyCacheKey)) {
        return;
      }
    } else {
      clearSocialCopyCache(socialCopyCacheKey);
      pendingSocialCopyRequests.delete(socialCopyCacheKey);
    }

    writeSocialCopyCache(socialCopyCacheKey, {
      status: "pending",
      startedAt: Date.now(),
    });
    pendingSocialCopyRequests.add(socialCopyCacheKey);
    socialCopyInFlightRef.current = true;
    setIsGeneratingCopy(true);
    setCopyError(null);

    try {
      const res = await fetch("/api/social-copy", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...headers },
        body: JSON.stringify({ brandContext, force }),
      });

      if (!res.ok) {
        const err = await res.json();
        const message = err.error ?? "Failed to generate copy.";
        setCopyError(message);
        writeSocialCopyCache(socialCopyCacheKey, { status: "error", error: message });
        return;
      }

      const data = (await res.json()) as SocialCopy;
      if (!isValidSocialCopy(data)) {
        const message =
          extractSocialCopyError(data.raw) ?? "Failed to generate valid social copy.";
        setCopyError(message);
        setSocialCopy(null);
        writeSocialCopyCache(socialCopyCacheKey, { status: "error", error: message });
        return;
      }

      setSocialCopy(data);
      writeSocialCopyCache(socialCopyCacheKey, { status: "success", data });
    } catch {
      const message = "Failed to generate social copy.";
      setCopyError(message);
      writeSocialCopyCache(socialCopyCacheKey, { status: "error", error: message });
    } finally {
      pendingSocialCopyRequests.delete(socialCopyCacheKey);
      socialCopyInFlightRef.current = false;
      setIsGeneratingCopy(false);
    }
  }, [brandContext, headers, socialCopy, socialCopyCacheKey]);

  useEffect(() => {
    const cached = readSocialCopyCache(socialCopyCacheKey);

    if (cached?.status === "success") {
      setSocialCopy(cached.data);
      setCopyError(null);
      return;
    }

    if (cached?.status === "error") {
      setSocialCopy(null);
      setCopyError(cached.error);
      return;
    }

    setSocialCopy(null);
    setCopyError(null);
  }, [socialCopyCacheKey]);

  useEffect(() => {
    if (!siteUrl) {
      return;
    }

    const cached = readSocialCopyCache(socialCopyCacheKey);
    if (cached?.status === "success" || cached?.status === "error" || cached?.status === "pending") {
      return;
    }

    if (pendingSocialCopyRequests.has(socialCopyCacheKey)) {
      return;
    }

    if (autoGeneratedKeysRef.current.has(socialCopyCacheKey)) {
      return;
    }

    autoGeneratedKeysRef.current.add(socialCopyCacheKey);
    void generateSocialCopy();
  }, [generateSocialCopy, siteUrl, socialCopyCacheKey]);

  // Download report
  async function downloadReport() {
    setIsDownloading(true);
    try {
      const reportData = {
        brandName: productAnalysis.brandName,
        siteUrl,
        oneLiner: productAnalysis.oneLiner,
        positioning: productAnalysis.positioning,
        targetAudience: productAnalysis.targetAudience,
        painPoints: productAnalysis.painPoints,
        differentiators: productAnalysis.differentiators,
        primaryCta: productAnalysis.primaryCta,
        brandVoice: productAnalysis.brandVoice,
        competitors: competitors.map((c) => {
          const analysis = competitorAnalyses.find((a) => a.domain === c.domain);
          return {
            name: c.name,
            domain: c.domain,
            positioning: analysis?.positioning ?? c.positioning,
            strengths: analysis?.strengths,
            weaknesses: analysis?.weaknesses,
          };
        }),
        insights,
        voiceDoc: brandVoiceDoc
          ? {
              identity: brandVoiceDoc.identity,
              principles: brandVoiceDoc.principles.map((p) => ({
                label: p.label,
                explanation: p.explanation,
              })),
              dos: brandVoiceDoc.dos,
              donts: brandVoiceDoc.donts,
            }
          : null,
      };

      const res = await fetch("/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...headers },
        body: JSON.stringify(reportData),
      });

      if (!res.ok) throw new Error("Failed to generate report");

      const html = await res.text();
      const blob = new Blob([html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      const win = window.open(url, "_blank");
      if (win) {
        win.addEventListener("load", () => {
          URL.revokeObjectURL(url);
        });
      }
    } catch {
      // Silently fail
    } finally {
      setIsDownloading(false);
    }
  }

  return (
    <div className="relative min-h-screen bg-[#050505] text-white font-[Inter,sans-serif]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,94,0,0.14),transparent_22%),radial-gradient(circle_at_top_right,rgba(255,255,255,0.04),transparent_22%),linear-gradient(180deg,#050505_0%,#090909_100%)]" />

      <header className="sticky top-0 z-40 px-6 pt-5 md:px-10 md:pt-6">
        <div className="mx-auto max-w-[1360px]">
          <div className="flex min-h-[78px] items-center justify-between rounded-full border border-white/10 bg-[#121212]/92 px-6 shadow-[0_22px_60px_rgba(0,0,0,0.28)] backdrop-blur-xl md:px-10">
            <div className="flex items-center gap-4">
              <Link
                href="/"
                className="text-[1.15rem] font-semibold tracking-[-0.05em] text-white transition hover:text-white/82"
              >
                Friday<span className="text-[#ff5e00]">.</span>
              </Link>
              <div className="hidden h-5 w-px bg-white/10 md:block" />
              <div className="hidden text-sm text-white/45 md:block">{domain}</div>
            </div>

            <button
              type="button"
              onClick={downloadReport}
              disabled={isDownloading}
              className="inline-flex items-center gap-2 rounded-full bg-[#ff5e00] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#e65400] disabled:opacity-50"
            >
              {isDownloading ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              Download Report
            </button>
          </div>
        </div>
      </header>

      <main className="relative z-10 mx-auto max-w-[1360px] px-6 py-8 md:px-10 md:py-10">
        <section className="rounded-[36px] border border-white/10 bg-[linear-gradient(180deg,#101521_0%,#0b1019_100%)] p-8 shadow-[0_34px_90px_rgba(15,23,42,0.18)] md:p-10">
          <div className="text-sm font-semibold uppercase tracking-[0.16em] text-[#ff8a3d]">
            Company workspace
          </div>
          <div className="mt-6 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <div className="max-w-[50rem]">
              <h1 className="text-[clamp(2.6rem,5vw,4.4rem)] font-semibold tracking-[-0.07em] text-white">
                {productAnalysis.brandName}
              </h1>
              <p className="mt-4 max-w-[44rem] text-[1.02rem] leading-[1.85] text-white/62">
                {productAnalysis.oneLiner}
              </p>
            </div>
            <div className="flex max-w-[28rem] flex-wrap gap-2">
              {productAnalysis.targetAudience.map((audience) => (
                <span
                  key={audience}
                  className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-xs font-medium text-white/64"
                >
                  {audience}
                </span>
              ))}
            </div>
          </div>
        </section>

        <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,0.75fr)]">
          <div className="space-y-6">
            <section className="rounded-[32px] border border-white/10 bg-[#101010] p-6 shadow-[0_22px_60px_rgba(0,0,0,0.22)]">
              <div className="mb-6 flex items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#ff5e00]/12 text-[#ff8a3d]">
                    <ImageIcon size={20} />
                  </div>
                  <div>
                    <h2 className="text-xl font-semibold tracking-[-0.03em] text-white">Image Generation</h2>
                    <p className="text-sm text-white/42">Brand graphics are intentionally paused</p>
                  </div>
                </div>
                <span className="rounded-full border border-[#ff5e00]/20 bg-[#ff5e00]/10 px-4 py-2 text-sm font-medium text-[#ff8a3d]">
                  Paused
                </span>
              </div>

              <div className="rounded-[24px] border border-white/10 bg-white/[0.03] p-8">
                <div className="flex items-start gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#ff5e00]/12 text-[#ff8a3d]">
                    <ImageIcon size={20} />
                  </div>
                  <div>
                    <div className="text-[1.02rem] font-semibold tracking-[-0.03em] text-white">
                      Image generation is paused
                    </div>
                    <p className="mt-2 max-w-[44rem] text-sm leading-7 text-white/58">
                      Friday will not generate poster or ad images right now. Social copy
                      stays active, but visual asset generation is deliberately turned off.
                    </p>
                  </div>
                </div>
              </div>
            </section>

            <section className="rounded-[32px] border border-white/10 bg-[#101010] p-6 shadow-[0_22px_60px_rgba(0,0,0,0.22)]">
              <div className="mb-6 flex items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#ff5e00]/12 text-[#ff8a3d]">
                    <FileText size={20} />
                  </div>
                  <div>
                    <h2 className="text-xl font-semibold tracking-[-0.03em] text-white">Social Copy</h2>
                    <p className="text-sm text-white/42">Ready-to-post content for your channels</p>
                  </div>
                </div>
                {!isGeneratingCopy && socialCopy && (
                  <button
                    type="button"
                    onClick={() => {
                      void generateSocialCopy({ force: true });
                    }}
                    className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-medium text-white/62 transition hover:border-white/20 hover:text-white"
                  >
                    <RefreshCw size={14} />
                    Regenerate
                  </button>
                )}
                {!isGeneratingCopy && !socialCopy && copyError && (
                  <button
                    type="button"
                    onClick={() => {
                      void generateSocialCopy({ force: true });
                    }}
                    className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-medium text-white/62 transition hover:border-white/20 hover:text-white"
                  >
                    <RefreshCw size={14} />
                    Retry
                  </button>
                )}
              </div>

              {isGeneratingCopy && (
                <div className="flex items-center gap-3 rounded-[24px] border border-white/10 bg-white/[0.03] p-8">
                  <Loader2 size={18} className="animate-spin text-[#ff8a3d]" />
                  <span className="text-sm text-white/58">Generating social copy...</span>
                </div>
              )}

              {copyError && (
                <div className="rounded-[24px] border border-[#7f1d1d] bg-[#2a0d0d] p-4 text-sm text-[#fca5a5]">
                  {copyError}
                </div>
              )}

              {socialCopy && (
                <div className="grid gap-4 xl:grid-cols-3">
                  <div className="rounded-[24px] border border-white/10 bg-[#151515] p-5">
                    <div className="mb-4 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Instagram size={16} className="text-[#ff8a3d]" />
                        <span className="text-sm font-semibold text-white">Instagram</span>
                      </div>
                      <CopyButton text={socialCopy.instagram} />
                    </div>
                    <p className="whitespace-pre-wrap text-sm leading-relaxed text-white/68">
                      {socialCopy.instagram || "No caption generated."}
                    </p>
                  </div>

                  <div className="rounded-[24px] border border-white/10 bg-[#151515] p-5">
                    <div className="mb-4 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Twitter size={16} className="text-[#ff8a3d]" />
                        <span className="text-sm font-semibold text-white">X</span>
                      </div>
                      <CopyButton text={socialCopy.x} />
                    </div>
                    <p className="whitespace-pre-wrap text-sm leading-relaxed text-white/68">
                      {socialCopy.x || "No post generated."}
                    </p>
                    <div className="mt-3 text-xs text-white/28">
                      {socialCopy.x.length}/280 characters
                    </div>
                  </div>

                  <div className="rounded-[24px] border border-white/10 bg-[#151515] p-5">
                    <div className="mb-4 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Linkedin size={16} className="text-[#ff8a3d]" />
                        <span className="text-sm font-semibold text-white">LinkedIn</span>
                      </div>
                      <CopyButton text={socialCopy.linkedin} />
                    </div>
                    <p className="whitespace-pre-wrap text-sm leading-relaxed text-white/68">
                      {socialCopy.linkedin || "No post generated."}
                    </p>
                  </div>
                </div>
              )}
            </section>
          </div>

          <div className="space-y-6">
            <section className="rounded-[32px] border border-white/10 bg-[#101010] p-6 shadow-[0_22px_60px_rgba(0,0,0,0.22)]">
              <div className="text-sm font-semibold uppercase tracking-[0.14em] text-[#ff8a3d]">
                Snapshot
              </div>
              <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-1">
                <div className="rounded-[24px] border border-white/10 bg-white/[0.03] p-5">
                  <div className="text-xs font-semibold uppercase tracking-[0.12em] text-white/38">Positioning</div>
                  <p className="mt-3 text-sm leading-relaxed text-white/68">{productAnalysis.positioning}</p>
                </div>
                <div className="rounded-[24px] border border-white/10 bg-white/[0.03] p-5">
                  <div className="text-xs font-semibold uppercase tracking-[0.12em] text-white/38">Competitors</div>
                  <div className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white">{competitors.length}</div>
                  <div className="mt-1 text-sm text-white/42">tracked in landscape</div>
                </div>
                <div className="rounded-[24px] border border-white/10 bg-white/[0.03] p-5">
                  <div className="text-xs font-semibold uppercase tracking-[0.12em] text-white/38">Opportunities</div>
                  <div className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white">{insights?.opportunities.length ?? 0}</div>
                  <div className="mt-1 text-sm text-white/42">campaign angles found</div>
                </div>
                <div className="rounded-[24px] border border-white/10 bg-white/[0.03] p-5">
                  <div className="text-xs font-semibold uppercase tracking-[0.12em] text-white/38">Brand Voice</div>
                  <div className="mt-3 text-sm leading-relaxed text-white/68">
                    {brandVoiceDoc?.identity ?? productAnalysis.brandVoice.join(", ")}
                  </div>
                </div>
              </div>
            </section>

            <section className="rounded-[32px] border border-white/10 bg-[#101010] p-6 shadow-[0_22px_60px_rgba(0,0,0,0.22)]">
              <div className="flex items-center justify-between gap-4">
                <div>
                  <div className="text-sm font-semibold uppercase tracking-[0.14em] text-[#ff8a3d]">
                    Differentiators
                  </div>
                  <h2 className="mt-2 text-xl font-semibold tracking-[-0.03em] text-white">
                    What stands out in the product
                  </h2>
                </div>
              </div>
              <div className="mt-5 grid gap-3">
                {productAnalysis.differentiators.map((differentiator, index) => (
                  <div key={index} className="rounded-[22px] border border-white/10 bg-white/[0.03] px-5 py-4">
                    <p className="text-sm leading-relaxed text-white/68">{differentiator}</p>
                  </div>
                ))}
              </div>
            </section>

            <section className="rounded-[32px] border border-white/10 bg-[#101010] p-6 shadow-[0_22px_60px_rgba(0,0,0,0.22)]">
              <div className="text-sm font-semibold uppercase tracking-[0.14em] text-[#ff8a3d]">
                Domain
              </div>
              <div className="mt-3 text-lg font-semibold tracking-[-0.03em] text-white">{domain}</div>
              <a
                href={siteUrl}
                target="_blank"
                rel="noreferrer"
                className="mt-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-medium text-white/62 transition hover:border-white/20 hover:text-white"
              >
                <Download size={14} />
                Open source website
              </a>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
